# PyCaret para Detecção de Outliers

# Instalação da biblioteca

In [ ]:
!pip install pycaret

In [ ]:
from pycaret.utils import enable_colab
enable_colab()

Colab mode enabled.

# Base de dados

- Mice Protein Expression: níveis de expressão de 77 proteínas/modificações de proteínas que produziram sinais detectáveis na fração nuclear do córtex
- Mais informações: https://archive.ics.uci.edu/ml/datasets/Mice+Protein+Expression

In [ ]:
from pycaret.datasets import get_data
dataset = get_data('mice')

  MouseID  DYRK1A_N   ITSN1_N    BDNF_N  ...  Genotype  Treatment  Behavior   class
0   309_1  0.503644  0.747193  0.430175  ...   Control  Memantine       C/S  c-CS-m
1   309_2  0.514617  0.689064  0.411770  ...   Control  Memantine       C/S  c-CS-m
2   309_3  0.509183  0.730247  0.418309  ...   Control  Memantine       C/S  c-CS-m
3   309_4  0.442107  0.617076  0.358626  ...   Control  Memantine       C/S  c-CS-m
4   309_5  0.434940  0.617430  0.358802  ...   Control  Memantine       C/S  c-CS-m

[5 rows x 82 columns]

In [ ]:
dataset.shape

(1080, 82)

In [ ]:
data = dataset.sample(frac=0.95, random_state=1)
data.shape

(1026, 82)

In [ ]:
data_unseen = dataset.drop(data.index)
data_unseen.shape

(54, 82)

In [ ]:
data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

# Configuração do ambiente

In [ ]:
from pycaret.anomaly import setup
experimento = setup(data, normalize = True, ignore_features = ['MouseID'], session_id = 123)

                               Description                 Value
0                               session_id                   123
1                            Original Data            (1026, 82)
2                           Missing Values                  True
3                         Numeric Features                    77
4                     Categorical Features                     4
5                         Ordinal Features                 False
6                High Cardinality Features                 False
7                  High Cardinality Method                  None
8                         Transformed Data            (1026, 91)
9                                 CPU Jobs                    -1
10                                 Use GPU                 False
11                          Log Experiment                 False
12                         Experiment Name  anomaly-default-name
13                                     USI                  1be9
14                         Imputation Type                simple
15          Iterative Imputation Iteration                  None
16                         Numeric Imputer                  mean
17      Iterative Imputation Numeric Model                  None
18                     Categorical Imputer                  mode
19  Iterative Imputation Categorical Model                  None
20           Unknown Categoricals Handling        least_frequent
21                               Normalize                  True
22                        Normalize Method                zscore
23                          Transformation                 False
24                   Transformation Method                  None
25                                     PCA                 False
26                              PCA Method                  None
27                          PCA Components                  None
28                     Ignore Low Variance                 False
29                     Combine Rare Levels                 False
30                    Rare Level Threshold                  None
31                         Numeric Binning                 False
32                         Remove Outliers                 False
33                      Outliers Threshold                  None
34                Remove Multicollinearity                 False
35             Multicollinearity Threshold                  None
36             Remove Perfect Collinearity                 False
37                              Clustering                 False
38                    Clustering Iteration                  None
39                     Polynomial Features                 False
40                       Polynomial Degree                  None
41                    Trignometry Features                 False
42                    Polynomial Threshold                  None
43                          Group Features                 False
44                       Feature Selection                 False
45                Feature Selection Method               classic
46            Features Selection Threshold                  None
47                     Feature Interaction                 False
48                           Feature Ratio                 False
49                   Interaction Threshold                  None

# Criação do modelo

In [ ]:
from pycaret.anomaly import models
models()

                                        Name                    Reference
ID
abod            Angle-base Outlier Detection        pyod.models.abod.ABOD
cluster       Clustering-Based Local Outlier      pyod.models.cblof.CBLOF
cof         Connectivity-Based Local Outlier          pyod.models.cof.COF
iforest                     Isolation Forest  pyod.models.iforest.IForest
histogram  Histogram-based Outlier Detection        pyod.models.hbos.HBOS
knn             K-Nearest Neighbors Detector          pyod.models.knn.KNN
lof                     Local Outlier Factor          pyod.models.lof.LOF
svm                   One-class SVM detector      pyod.models.ocsvm.OCSVM
pca             Principal Component Analysis          pyod.models.pca.PCA
mcd           Minimum Covariance Determinant          pyod.models.mcd.MCD
sod               Subspace Outlier Detection          pyod.models.sod.SOD
sos             Stochastic Outlier Selection          pyod.models.sos.SOS

In [ ]:
from pycaret.anomaly import create_model
iforest = create_model('iforest') # Isolation Forest

In [ ]:
print(iforest)

IForest(behaviour='new', bootstrap=False, contamination=0.05,
    max_features=1.0, max_samples='auto', n_estimators=100, n_jobs=-1,
    random_state=123, verbose=0)

In [ ]:
from pycaret.anomaly import assign_model
iforest_results = assign_model(iforest)
iforest_results

        MouseID  DYRK1A_N   ITSN1_N  ...   class  Anomaly  Anomaly_Score
0     50810F_14  0.399414  0.496445  ...  c-CS-s        0      -0.016360
1       3418_11  0.271309  0.442069  ...  t-SC-m        0      -0.023039
2        3424_9  0.320669  0.504921  ...  c-SC-s        0      -0.100661
3        3520_7  0.619721  0.739200  ...  c-CS-m        0      -0.089228
4        3429_5  0.799383  0.889155  ...  t-CS-m        0      -0.069321
...         ...       ...       ...  ...     ...      ...            ...
1021     3424_5  0.387123  0.557831  ...  c-SC-s        0      -0.109747
1022   J2292_10  0.294578  0.398053  ...  c-SC-s        0      -0.095107
1023    3502_10  0.262447  0.544304  ...  t-SC-m        0      -0.021365
1024    3423_12  0.245222  0.460812  ...  c-SC-s        0      -0.100601
1025    3498_12  0.718856  0.935593  ...  t-CS-s        0      -0.082804

[1026 rows x 84 columns]

# Visualização e previsão

In [ ]:
from pycaret.anomaly import plot_model
plot_model(iforest)

In [ ]:
from pycaret.anomaly import predict_model
unseen_predictions = predict_model(iforest, data=data_unseen)
unseen_predictions.head()

   MouseID  DYRK1A_N   ITSN1_N  ...   class  Anomaly  Anomaly_Score
0    311_1  0.743118  0.862653  ...  c-CS-m        1       0.001644
1   311_11  0.538413  0.701865  ...  c-CS-m        1       0.030889
2  3520_10  0.638367  0.716735  ...  c-CS-m        0      -0.075486
3   3521_7  0.571314  0.749634  ...  c-CS-m        0      -0.085377
4  3521_10  0.538125  0.702343  ...  c-CS-m        0      -0.091045

[5 rows x 84 columns]

# Salvar e carregar o modelo

In [ ]:
from pycaret.anomaly import save_model
save_model(iforest,'Final IForest')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True,
                                       features_todrop=['MouseID'],
                                       id_columns=[], ml_usecase='regression',
                                       numerical_features=[],
                                       target='UNSUPERVISED_DUMMY_TARGET',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='most frequent',
                                 fill_value_categorical=None,
                                 fill_value_numer...
                 ('fix_perfect', 'passthrough'),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  IForest(behaviour='new', bootstrap=False, contamination=0.05,
     max_features=1.0, max_samples='auto', n_estimators=100, n_jobs=-1,
     random_state=123, verbose=0)]],
          verbose=False), 'Final IForest.pkl')

In [ ]:
from pycaret.anomaly import load_model
saved_iforest = load_model('Final IForest')

Transformation Pipeline and Model Successfully Loaded

In [ ]:
new_prediction = predict_model(saved_iforest, data=data_unseen)
new_prediction

      MouseID  DYRK1A_N   ITSN1_N  ...   class  Anomaly  Anomaly_Score
0       311_1  0.743118  0.862653  ...  c-CS-m        1       0.001644
1      311_11  0.538413  0.701865  ...  c-CS-m        1       0.030889
2     3520_10  0.638367  0.716735  ...  c-CS-m        0      -0.075486
3      3521_7  0.571314  0.749634  ...  c-CS-m        0      -0.085377
4     3521_10  0.538125  0.702343  ...  c-CS-m        0      -0.091045
5       294_6  0.309966  0.468068  ...  c-SC-m        0      -0.091158
6      3419_2  0.288121  0.463549  ...  c-SC-m        0      -0.093337
7     3419_15  0.196671  0.364057  ...  c-SC-m        0      -0.053150
8     3500_11  0.272919  0.426544  ...  c-SC-m        0      -0.069087
9      3503_4  0.316411  0.442410  ...  c-SC-m        0      -0.059853
10    3503_13  0.290638  0.333142  ...  c-SC-m        0      -0.021757
11    3477_14  0.408648  0.567888  ...  c-CS-s        0      -0.059162
12     3478_2  0.427417  0.723227  ...  c-CS-s        0      -0.030876
13     3478_5  0.385190  0.606740  ...  c-CS-s        0      -0.065840
14    3480_13  0.267157  0.391403  ...  c-CS-s        0      -0.019002
15   50810A_9  0.301765  0.536569  ...  c-CS-s        0      -0.049656
16  50810F_12  0.390873  0.512566  ...  c-CS-s        0      -0.001523
17     3423_7  0.266933  0.513347  ...  c-SC-s        0      -0.089376
18     3424_4  0.238413  0.359105  ...  c-SC-s        1       0.012957
19     3488_3  0.301695  0.523850  ...  c-SC-s        0      -0.078268
20    3488_14  0.237231  0.354680  ...  c-SC-s        0      -0.035149
21     3489_4  0.262720  0.471840  ...  c-SC-s        0      -0.091394
22     3489_6  0.260145  0.465398  ...  c-SC-s        0      -0.083477
23     3516_3  0.223315  0.369830  ...  c-SC-s        0      -0.053784
24    J2292_8  0.252386  0.402437  ...  c-SC-s        0      -0.100787
25    3414_11  0.625976  0.806894  ...  t-CS-m        0      -0.070315
26     3416_2  0.673085  0.877280  ...  t-CS-m        0      -0.085123
27    3416_11  0.406920  0.520235  ...  t-CS-m        0      -0.032326
28     3429_7  0.629769  0.741792  ...  t-CS-m        0      -0.069351
29    3429_13  0.489164  0.644807  ...  t-CS-m        0      -0.022884
30     3504_4  0.887377  0.972656  ...  t-CS-m        0      -0.065089
31     3505_4  0.814391  1.124141  ...  t-CS-m        0      -0.045540
32     3522_9  0.569612  0.713120  ...  t-CS-m        0      -0.083022
33      363_6  0.694371  0.918983  ...  t-CS-m        0      -0.066638
34     293_11  0.226645  0.490252  ...  t-SC-m        0      -0.053814
35     3411_9  0.284056  0.510721  ...  t-SC-m        0      -0.092854
36    3418_15  0.252289  0.402905  ...  t-SC-m        0      -0.019875
37     3501_2  0.343242  0.703295  ...  t-SC-m        0      -0.029403
38     3501_4  0.326309  0.653168  ...  t-SC-m        0      -0.063013
39    3530_13  0.278592  0.522287  ...  t-SC-m        0      -0.030946
40     3606_5  0.403120  0.649020  ...  t-SC-m        0      -0.077329
41    18899_8  0.404483  0.591862  ...  t-CS-s        0      -0.059632
42    3483_14  0.425366  0.587122  ...  t-CS-s        0      -0.021520
43   50810B_6  0.576347  0.800773  ...  t-CS-s        0      -0.052681
44   50810B_8  0.554878  0.748556  ...  t-CS-s        0      -0.072879
45  50810B_15  0.474926  0.601089  ...  t-CS-s        0      -0.050344
46  50810C_14  0.423483  0.734913  ...  t-CS-s        0      -0.082693
47   50810E_4  0.537876  0.805816  ...  t-CS-s        0      -0.069667
48     3425_1  0.378700  0.738617  ...  t-SC-s        0      -0.081540
49     3425_5  0.364357  0.603839  ...  t-SC-s        0      -0.071663
50    3491_10  0.422992  0.573768  ...  t-SC-s        0      -0.074859
51    3491_12  0.373621  0.561337  ...  t-SC-s        0      -0.084316
52    3517_12  0.296432  0.430919  ...  t-SC-s        0      -0.061260
53   J1291_12  0.204136  0.401779  ...  t-SC-s        0      -0.070629

[54 rows x 84 columns]

In [ ]:
outliers = new_prediction[new_prediction['Anomaly'] == 1]
outliers

   MouseID  DYRK1A_N   ITSN1_N  ...   class  Anomaly  Anomaly_Score
0    311_1  0.743118  0.862653  ...  c-CS-m        1       0.001644
1   311_11  0.538413  0.701865  ...  c-CS-m        1       0.030889
18  3424_4  0.238413  0.359105  ...  c-SC-s        1       0.012957

[3 rows x 84 columns]

In [ ]:
outliers.to_csv('outliers.csv')