# Processamento de linguagem natural Modelagem de Tópicos usando PyCaret

# Instalação da biblioteca

In [ ]:
!pip install pycaret

In [ ]:
from pycaret.utils import enable_colab
enable_colab()

Colab mode enabled.

In [ ]:
!python -m spacy download en_core_web_sm
!python -m textblob.download_corpora

# Base de dados

- Kiva Microfunds https://www.kiva.org/

In [ ]:
from pycaret.datasets import get_data
dataset = get_data('kiva')

              country  ... status
0  Dominican Republic  ...      0
1  Dominican Republic  ...      0
2  Dominican Republic  ...      0
3  Dominican Republic  ...      0
4  Dominican Republic  ...      0

[5 rows x 7 columns]

In [ ]:
dataset.shape

(6818, 7)

In [ ]:
data = dataset.sample(1000, random_state=1).reset_index(drop=True)
data.shape

(1000, 7)

# Configuração do ambiente

In [ ]:
from pycaret.nlp import setup
experimento = setup(data = data, target = 'en', session_id = 123)

# Criação do modelo (topic model)

In [ ]:
from pycaret.nlp import models
models()

                                  Name                  Reference
ID
lda        Latent Dirichlet Allocation     gensim/models/ldamodel
lsi           Latent Semantic Indexing     gensim/models/lsimodel
hdp     Hierarchical Dirichlet Process     gensim/models/hdpmodel
rp                  Random Projections      gensim/models/rpmodel
nmf  Non-Negative Matrix Factorization  sklearn.decomposition.NMF

In [ ]:
from pycaret.nlp import create_model
lda = create_model('lda')

In [ ]:
print(lda)

LdaModel(num_terms=4581, num_topics=4, decay=0.5, chunksize=100)

In [ ]:
lda2 = create_model('lda', num_topics = 6, multi_core = True)
print(lda2)

LdaModel(num_terms=4581, num_topics=6, decay=0.5, chunksize=100)

# Visualização e previsão

In [ ]:
from pycaret.nlp import assign_model
lda_results = assign_model(lda)
lda_results

                country  ... Perc_Dominant_Topic
0    Dominican Republic  ...                0.99
1                 Kenya  ...                0.60
2                 Kenya  ...                0.79
3                 Kenya  ...                0.83
4               Ecuador  ...                0.51
..                  ...  ...                 ...
995  Dominican Republic  ...                0.96
996               Kenya  ...                0.58
997               Kenya  ...                0.78
998             Ecuador  ...                0.90
999  Dominican Republic  ...                0.67

[1000 rows x 13 columns]

In [ ]:
from pycaret.nlp import plot_model
plot_model(plot = 'bigram')

In [ ]:
plot_model(lda, plot = 'frequency', topic_num = 'Topic 1')

In [ ]:
plot_model(lda, plot = 'frequency', topic_num = 'Topic 2')

In [ ]:
plot_model(lda, plot = 'topic_distribution')

In [ ]:
# T-distributed Stochastic Neighbor Embedding
plot_model(lda, plot = 'tsne')

In [ ]:
from pycaret.nlp import evaluate_model
evaluate_model(lda)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Frequency Plot', 'freque…

# Salvar e carregar o modelo

In [ ]:
from pycaret.nlp import save_model
save_model(lda,'Final Lda')

Model Succesfully Saved

(<gensim.models.ldamodel.LdaModel at 0x7f9f06701f10>, 'Final Lda.pkl')

In [ ]:
from pycaret.nlp import load_model
saved_lda = load_model('Final Lda')

Model Sucessfully Loaded